library(shiny)


shinyServer(function(input,output){
    DT_options <- list(
        pageLength=1000,
        scrollX=TRUE,
        ordering=FALSE,
        select=FALSE,
        columnDefs=list(list(width="6rem",targets=0))
    )
    
    output$ITmedia=renderDT(
        data$ITmedia,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$ITmedia_news=renderDT(
        data$ITmedia_news,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$ITmedia_pcuser=renderDT(
        data$ITmedia_pcuser,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$ITmedia_enterprise=renderDT(
        data$ITmedia_enterprise,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$ITmedia_mobile=renderDT(
        data$ITmedia_mobile,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$ITmedia_business=renderDT(
        data$ITmedia_business,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$atmarkit=renderDT(
        data$atmarkit,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$netlabo=renderDT(
        data$netlabo,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$ascii=renderDT(
        data$ascii,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$ascii_ai=renderDT(
        data$ascii_ai,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$ascii_biz=renderDT(
        data$ascii_biz,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$ascii_tech=renderDT(
        data$ascii_tech,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$ascii_akiba=renderDT(
        data$ascii_akiba,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$impress=renderDT(
        data$impress,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$impress_internet=renderDT(
        data$impress_internet,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$impress_pc=renderDT(
        data$impress_pc,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$impress_akiba=renderDT(
        data$impress_akiba,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$impress_ktai=renderDT(
        data$impress_ktai,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$impress_cloud=renderDT(
        data$impress_cloud,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
    output$impress_hobby=renderDT(
        data$impress_hobby,
        class="row-border",colnames="",rownames=FALSE,escape=FALSE,options=DT_options
    )
})
